import "./globals.css";
import "./styles/index.scss"
import 'swiper/css';
import Footer from "@/components/core/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body
      className={`antialiased`}
    >
    {children}

    <Footer/>
    </body>
    </html>
  );
}
